steps:
  - label: ':bundler: Update Dependencies'
    command: 'gem update --system && gem install bundler && bundle install'
    
  - wait
  
  - label: ':fastlane: Run Tests'
    command: 'bundle exec fastlane test'
