default_platform(:ios)

before_all do
  update_fastlane
end

desc "Runs the unit tests to ensure the build is working"
lane :test do
  scan(scheme: "TOReachabilityTests", devices: ["iPhone SE"], clean: true)
end
